### ISSUE TITLE
村庄无法生成

### ISSUE THREAD

**Issue by olddrive** [wode490390/BetterVanillaGenerator#1]
村庄无法生成

**Comment by wode490390** [comment]
村庄等结构将在另一个插件中实现

**Comment by good777LUCKY** [comment]
> 마을과 같은 구조는 다른 플러그인에서 구현됩니다

Can you recommend Village plugin for Nukkit? I can't find it.

**Comment by good777LUCKY** [comment]
> 村庄等结构将在另一个插件中实现

Can you recommend Village plugin for Nukkit? I can't find it.

**Comment by wode490390** [comment]
@good777LUCKY It has not been made public.
