### ISSUE TITLE
Terrain Generate Bug

### ISSUE THREAD

**Issue by good777LUCKY** [wode490390/BetterVanillaGenerator#3]
I think this is a bug.
![Screenshot_20200401-124008_Minecraft1](https://user-images.githubusercontent.com/43497313/78097311-eea33f80-7416-11ea-8006-537f5a68053a.png)

**Comment by wode490390** [comment]
What's your seed?

**Comment by good777LUCKY** [comment]
1574845404389

**Comment by good777LUCKY** [comment]
More bugs..
![Screenshot_20200402-152553_Minecraft](https://user-images.githubusercontent.com/43497313/78228550-cfd1a580-7509-11ea-8676-50434a026f0f.jpg)

**Comment by good777LUCKY** [comment]
And more bugs..
![Screenshot_20200402-152553_Minecraft](https://user-images.githubusercontent.com/43497313/78241788-f13b8d00-751b-11ea-802a-ec92920247fb.png)

**Comment by wode490390** [comment]
> 1574845404389

I can't find the same biome at the same coordinates

**Comment by good777LUCKY** [comment]
i will check seed again

**Comment by wode490390** [comment]
Confirmed this issue, working on it.

**Comment by wode490390** [comment]
Fixed in https://github.com/wode490390/BetterVanillaGenerator/commit/9a1794cf61048c9d1c59ae47997d15d5f0ecd52c.
